# Generated by Django 4.2.4 on 2023-08-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flooring',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flooring',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='furniture',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='furniture',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
